### ISSUE TITLE
Disable Sepia and Night mode

### ISSUE THREAD

**Issue by shubhamk008** [healthyregions/sdohplace-toolkit#5]
Currently, the default theme is white for which the CSS definitions have been written. When a user clicks on Sepia or Night mode, the definitions don't work well. Example in the screenshot. So that's why we were looking to hide Sepia and Night mode altogether.

![image](https://github.com/healthyregions/sdhoplace-toolkit/assets/12235388/ec761d62-36eb-4293-9450-8a443e2a3d63)

**Comment by mradamcox** [comment]
In here https://rdrr.io/github/rstudio/bookdown/f/inst/examples/03-formats.Rmd I found you can disable the font button entirely with `fontsettings: null`. This removes the ability to change the font size, etc, so that's the tradeoff.

**Comment by mradamcox** [comment]
@shubhamk008 I've fixed a few things so now dark and sepia modes look a lot better. Can you check it out and close this ticket or suggest more changes that need to happen?

**Comment by shubhamk008** [comment]
This looks fantastic! Thank you for the update. We can close this ticket now.
